version: '3'

services:
  nginx:
    image: 'nginx:latest'
    container_name:  nginx
    volumes:
    - ./nginx:/etc/nginx/conf.d/
    - ./html:/usr/share/nginx/html/
    ports:
    - "80:80"
    depends_on:
      - app
  app:
    image: 'app:1.0'
    container_name: app